# Generated by Django 4.1 on 2022-09-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_extera_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Meassage',
            new_name='meassage',
        ),
        migrations.AlterField(
            model_name='extera_images',
            name='title',
            field=models.CharField(default='timezone', max_length=200),
            preserve_default=False,
        ),
    ]
